# roles/rhbase/tasks/security.yml
#
# Basic security settings
---
- name: Security | Make sure SELinux is Enforcing
  selinux:
    policy: targeted
    state: "{{ rhbase_selinux_state }}"
  tags:
    - rhbase
    - security

- name: Security | Make sure the firewall is running
  service:
    name: firewalld
    state: started
    enabled: yes
  tags:
    - rhbase
    - security

- name: Security | Make sure basic services can pass through firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - dhcpv6-client
    - ssh
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security

- name: Security | Make sure user specified services can pass through firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ rhbase_firewall_allow_services }}"
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security

- name: Security | Make sure user specified ports can pass through firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ rhbase_firewall_allow_ports }}"
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security
- name: Security | Make sure specified interfaces are added
  firewalld:
    interface: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  with_items: "{{ rhbase_firewall_interfaces }}"
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security
- name: Update van SSH configuratie om veiliger te zijn.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port 2849"
      notify: restart sshd


- name: restart sshd
  service: 
    name: sshd
    state: restarted
     
- name: Installatie fail2ban (RedHat).
  yum: name=fail2ban state=present enablerepo=epel
  when: ansible_os_family == 'RedHat'

- name: Installatie fail2ban (Debian).
  apt: name=fail2ban state=present
  when: ansible_os_family == 'Debian'

- name: Zorgt ervoor dat fail2ban runt en enabled is bij het booten.
  service: name=fail2ban state=started enabled=yes
