# roles/rh-base/handlers/main.yml
---

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: restart fail2ban
  service: 
    name: fail2ban 
    state: restarted
- name: restart ssh
  service:
    name: sshd
    state: restarted
- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted